package BiblioTech_AlpizarQuesada_ISemestre_2018;

import domain.Audiovisual;
import domain.Loan;
import file.AudiovisualFile;
import file.LoanFile;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LoanAudiovisual extends javax.swing.JFrame {

   File archivoLoan;
    File fileAudiovisual;
    LoanFile loanFile;
    AudiovisualFile audiovisualFile;
    ArrayList<Audiovisual> audiovisualArray;

    public LoanAudiovisual() throws FileNotFoundException, IOException, ClassNotFoundException {
        initComponents();
       

      lb_messageLoan.setVisible(false);
       fileAudiovisual= new File("Audiovisual.dat");
        audiovisualFile = new AudiovisualFile(fileAudiovisual);
       audiovisualArray= audiovisualFile.getStudentList();
        txa_information.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_codeLoanAudiovisual = new javax.swing.JLabel();
        tf_codeloanAudiovisual = new javax.swing.JTextField();
        lb_nameLoan = new javax.swing.JLabel();
        tf_nameLoan = new javax.swing.JTextField();
        lb_idLoanAudiovisual = new javax.swing.JLabel();
        tf_idLoanAudiovisual = new javax.swing.JTextField();
        lb_dateLoanAudiovisual = new javax.swing.JLabel();
        fechaInicialAudiovisual = new com.toedter.calendar.JDateChooser();
        lb_nameLoanAudiovisual = new javax.swing.JLabel();
        tfx_searchAudiovisual = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_information = new javax.swing.JTextArea();
        btn_registerLoanAudiovisual = new javax.swing.JButton();
        lb_messageLoan = new javax.swing.JLabel();
        lb_image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItenLibrary = new javax.swing.JMenu();
        menuItemStudent = new javax.swing.JMenuItem();
        menuItemLibrary = new javax.swing.JMenuItem();
        menuItemAudiovisual = new javax.swing.JMenuItem();
        menuLoan = new javax.swing.JMenu();
        menuItemSlect = new javax.swing.JMenuItem();
        menuItemReturn = new javax.swing.JMenuItem();
        menuItemTableStudent = new javax.swing.JMenu();
        menuItemRegisterStudent = new javax.swing.JMenuItem();
        menuItemRegisterBook = new javax.swing.JMenuItem();
        menuItemRegisterAudiovisual = new javax.swing.JMenuItem();
        MenuItem_LoanRegister = new javax.swing.JMenuItem();
        menuSystem = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_codeLoanAudiovisual.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_codeLoanAudiovisual.setForeground(new java.awt.Color(255, 255, 255));
        lb_codeLoanAudiovisual.setText("Code");
        getContentPane().add(lb_codeLoanAudiovisual);
        lb_codeLoanAudiovisual.setBounds(830, 300, 75, 29);

        tf_codeloanAudiovisual.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        tf_codeloanAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codeloanAudiovisualActionPerformed(evt);
            }
        });
        tf_codeloanAudiovisual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codeloanAudiovisualKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_codeloanAudiovisualKeyReleased(evt);
            }
        });
        getContentPane().add(tf_codeloanAudiovisual);
        tf_codeloanAudiovisual.setBounds(1040, 290, 350, 33);

        lb_nameLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_nameLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_nameLoan.setText("Student Name");
        getContentPane().add(lb_nameLoan);
        lb_nameLoan.setBounds(820, 130, 166, 29);

        tf_nameLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameLoanActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nameLoan);
        tf_nameLoan.setBounds(1040, 130, 348, 29);

        lb_idLoanAudiovisual.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_idLoanAudiovisual.setForeground(new java.awt.Color(255, 255, 255));
        lb_idLoanAudiovisual.setText("Id");
        getContentPane().add(lb_idLoanAudiovisual);
        lb_idLoanAudiovisual.setBounds(830, 220, 55, 28);
        getContentPane().add(tf_idLoanAudiovisual);
        tf_idLoanAudiovisual.setBounds(1040, 210, 348, 32);

        lb_dateLoanAudiovisual.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_dateLoanAudiovisual.setForeground(new java.awt.Color(255, 255, 255));
        lb_dateLoanAudiovisual.setText("Date Loan");
        getContentPane().add(lb_dateLoanAudiovisual);
        lb_dateLoanAudiovisual.setBounds(820, 380, 135, 39);
        getContentPane().add(fechaInicialAudiovisual);
        fechaInicialAudiovisual.setBounds(1040, 380, 348, 32);

        lb_nameLoanAudiovisual.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_nameLoanAudiovisual.setForeground(new java.awt.Color(255, 255, 255));
        lb_nameLoanAudiovisual.setText("Name or code of the Audiovisual");
        getContentPane().add(lb_nameLoanAudiovisual);
        lb_nameLoanAudiovisual.setBounds(310, 130, 1634, 27);

        tfx_searchAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx_searchAudiovisualActionPerformed(evt);
            }
        });
        tfx_searchAudiovisual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfx_searchAudiovisualKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx_searchAudiovisualKeyTyped(evt);
            }
        });
        getContentPane().add(tfx_searchAudiovisual);
        tfx_searchAudiovisual.setBounds(310, 220, 340, 30);

        txa_information.setEditable(false);
        txa_information.setColumns(20);
        txa_information.setRows(5);
        txa_information.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txa_informationKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txa_information);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 340, 340, 296);

        btn_registerLoanAudiovisual.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        btn_registerLoanAudiovisual.setText("Loan");
        btn_registerLoanAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerLoanAudiovisualActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registerLoanAudiovisual);
        btn_registerLoanAudiovisual.setBounds(1240, 760, 159, 41);

        lb_messageLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_messageLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_messageLoan.setText("El prestamo se realizo con exito");
        getContentPane().add(lb_messageLoan);
        lb_messageLoan.setBounds(330, 680, 590, 40);

        lb_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo22_1.png"))); // NOI18N
        getContentPane().add(lb_image);
        lb_image.setBounds(-20, -420, 2040, 1400);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuItenLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nota.png"))); // NOI18N
        menuItenLibrary.setText("Register");

        menuItemStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        menuItemStudent.setText("Students");
        menuItemStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStudentActionPerformed(evt);
            }
        });
        menuItenLibrary.add(menuItemStudent);

        menuItemLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.png"))); // NOI18N
        menuItemLibrary.setText("Books");
        menuItemLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLibraryActionPerformed(evt);
            }
        });
        menuItenLibrary.add(menuItemLibrary);

        menuItemAudiovisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/audiovisual.png"))); // NOI18N
        menuItemAudiovisual.setText("Audiovisual");
        menuItemAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAudiovisualActionPerformed(evt);
            }
        });
        menuItenLibrary.add(menuItemAudiovisual);

        jMenuBar1.add(menuItenLibrary);

        menuLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loan.png"))); // NOI18N
        menuLoan.setText("Loan");

        menuItemSlect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clave.png"))); // NOI18N
        menuItemSlect.setText("Verify");
        menuItemSlect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSlectActionPerformed(evt);
            }
        });
        menuLoan.add(menuItemSlect);

        menuItemReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espalda (1).png"))); // NOI18N
        menuItemReturn.setText("Return");
        menuItemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReturnActionPerformed(evt);
            }
        });
        menuLoan.add(menuItemReturn);

        jMenuBar1.add(menuLoan);

        menuItemTableStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nota.png"))); // NOI18N
        menuItemTableStudent.setText("Records");

        menuItemRegisterStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        menuItemRegisterStudent.setText("Students");
        menuItemRegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterStudentActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(menuItemRegisterStudent);

        menuItemRegisterBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.png"))); // NOI18N
        menuItemRegisterBook.setText("Books");
        menuItemRegisterBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterBookActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(menuItemRegisterBook);

        menuItemRegisterAudiovisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/audiovisual.png"))); // NOI18N
        menuItemRegisterAudiovisual.setText("Audiovisual");
        menuItemRegisterAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterAudiovisualActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(menuItemRegisterAudiovisual);

        MenuItem_LoanRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espalda (1).png"))); // NOI18N
        MenuItem_LoanRegister.setText("Loan");
        MenuItem_LoanRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_LoanRegisterActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(MenuItem_LoanRegister);

        jMenuBar1.add(menuItemTableStudent);

        menuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro (1).png"))); // NOI18N
        menuSystem.setText("System");

        menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuSystem.add(menuItemAbout);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuSystem.add(menuItemExit);

        jMenuBar1.add(menuSystem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStudentActionPerformed
        StudentRegister sr = new StudentRegister();
        sr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemStudentActionPerformed

    private void menuItemLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLibraryActionPerformed
        BookRegister br = new BookRegister();
        br.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemLibraryActionPerformed

    private void menuItemAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAudiovisualActionPerformed
        AudiovisualRegister av = new AudiovisualRegister();
        av.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAudiovisualActionPerformed

    private void menuItemSlectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSlectActionPerformed
        LoanRegister lr = new LoanRegister();
        lr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemSlectActionPerformed

    private void menuItemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReturnActionPerformed
        ReturnBook rb;

        try {
            rb = new ReturnBook();
            rb.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(LoanAudiovisual.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_menuItemReturnActionPerformed

    private void menuItemRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterStudentActionPerformed
        TableStudents ts;

        try {
            ts = new TableStudents();
            ts.setVisible(true);
            this.setVisible(false);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuItemRegisterStudentActionPerformed

    private void menuItemRegisterBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterBookActionPerformed

        TableBook tb;

        try {
            tb = new TableBook();
            tb.setVisible(true);
            this.setVisible(false);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuItemRegisterBookActionPerformed

    private void menuItemRegisterAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterAudiovisualActionPerformed
        TableAudiovisual ta;

        try {
            ta = new TableAudiovisual();
            ta.setVisible(true);
            this.setVisible(false);
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_menuItemRegisterAudiovisualActionPerformed

    private void MenuItem_LoanRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_LoanRegisterActionPerformed
        TableLoan tl;

        try {
            tl = new TableLoan();
            tl.setVisible(true);
            this.setVisible(false);
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_MenuItem_LoanRegisterActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        About ab = new About();
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void tf_codeloanAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codeloanAudiovisualActionPerformed

    }//GEN-LAST:event_tf_codeloanAudiovisualActionPerformed

    private void tf_codeloanAudiovisualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeloanAudiovisualKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_codeloanAudiovisualKeyPressed

    private void tf_codeloanAudiovisualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeloanAudiovisualKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_codeloanAudiovisualKeyReleased

    private void tf_nameLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameLoanActionPerformed

    private void tfx_searchAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx_searchAudiovisualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx_searchAudiovisualActionPerformed

    private void tfx_searchAudiovisualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx_searchAudiovisualKeyReleased
        txa_information.setText("");

        String cadenainformativa = "";
        for (int i = 0; i < audiovisualArray.size(); i++) {
            if (audiovisualArray.get(i).search(tfx_searchAudiovisual.getText().toUpperCase())) {
                cadenainformativa += "\n" + audiovisualArray.get(i).toString() + "\n";
            }
        }
        txa_information.setText(cadenainformativa);

    }//GEN-LAST:event_tfx_searchAudiovisualKeyReleased

    private void tfx_searchAudiovisualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx_searchAudiovisualKeyTyped

    }//GEN-LAST:event_tfx_searchAudiovisualKeyTyped

    private void txa_informationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txa_informationKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txa_informationKeyReleased

    private void btn_registerLoanAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerLoanAudiovisualActionPerformed
        archivoLoan = new File("Loan.dat");
        try {
            String formato = fechaInicialAudiovisual.getDateFormatString();
            Date fechainicial = fechaInicialAudiovisual.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);

            //            String format=fechaFinal.getDateFormatString();
            //            Date fechafinal= fechaFinal.getDate();
            //            SimpleDateFormat simDateF= new SimpleDateFormat(format);
            //
            loanFile = new LoanFile(archivoLoan);
            Loan loan = new Loan(tf_nameLoan.getText(), tf_idLoanAudiovisual.getText(), tf_codeloanAudiovisual.getText(),
                    "" + sdf.format(fechainicial));

            loanFile.addEndRecord(loan);
            lb_messageLoan.setVisible(true);
            lb_messageLoan.setText("The loan originated correctly");
            if (loanFile.quantityAvailable(tf_codeloanAudiovisual.getText())) {

            } else {
                lb_messageLoan.setText("The audiovisual is not available");
            }

            tf_codeloanAudiovisual.setText("");
            tf_idLoanAudiovisual.setText("");
            tf_nameLoan.setText("");
            tfx_searchAudiovisual.setText("");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_registerLoanAudiovisualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAudiovisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAudiovisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAudiovisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAudiovisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new LoanAudiovisual().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(LoanAudiovisual.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_LoanRegister;
    private javax.swing.JButton btn_registerLoanAudiovisual;
    private com.toedter.calendar.JDateChooser fechaInicialAudiovisual;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_codeLoanAudiovisual;
    private javax.swing.JLabel lb_dateLoanAudiovisual;
    private javax.swing.JLabel lb_idLoanAudiovisual;
    private javax.swing.JLabel lb_image;
    private javax.swing.JLabel lb_messageLoan;
    private javax.swing.JLabel lb_nameLoan;
    private javax.swing.JLabel lb_nameLoanAudiovisual;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemAudiovisual;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLibrary;
    private javax.swing.JMenuItem menuItemRegisterAudiovisual;
    private javax.swing.JMenuItem menuItemRegisterBook;
    private javax.swing.JMenuItem menuItemRegisterStudent;
    private javax.swing.JMenuItem menuItemReturn;
    private javax.swing.JMenuItem menuItemSlect;
    private javax.swing.JMenuItem menuItemStudent;
    private javax.swing.JMenu menuItemTableStudent;
    private javax.swing.JMenu menuItenLibrary;
    private javax.swing.JMenu menuLoan;
    private javax.swing.JMenu menuSystem;
    private javax.swing.JTextField tf_codeloanAudiovisual;
    private javax.swing.JTextField tf_idLoanAudiovisual;
    private javax.swing.JTextField tf_nameLoan;
    private javax.swing.JTextField tfx_searchAudiovisual;
    private javax.swing.JTextArea txa_information;
    // End of variables declaration//GEN-END:variables
}
