package BiblioTech_AlpizarQuesada_ISemestre_2018;

import domain.Books;
import domain.Loan;
import file.LoanFile;
import file.MaterialFile;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LoanBook extends javax.swing.JFrame {

    File archivoBooks;
    File archivoLoan;

    LoanFile loanFile;
    MaterialFile materialFile;
    ArrayList<Books> book;

    /**
     * Creates new form LoanBook
     */
    public LoanBook() throws FileNotFoundException, IOException, ClassNotFoundException {

        initComponents();
       
        this.setExtendedState(LoanBook.MAXIMIZED_BOTH);
        lb_messageLoan.setVisible(false);
        archivoBooks = new File("Books.dat");
        materialFile = new MaterialFile(archivoBooks);
        book = materialFile.getBookList();
        txa_information.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nameLoanBook = new javax.swing.JLabel();
        tfx_search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_information = new javax.swing.JTextArea();
        tf_codeloan = new javax.swing.JTextField();
        lb_codeLoan = new javax.swing.JLabel();
        lb_nameLoan = new javax.swing.JLabel();
        tf_nameLoan = new javax.swing.JTextField();
        lb_idLoan = new javax.swing.JLabel();
        tf_idLoan = new javax.swing.JTextField();
        lb_dateLoan = new javax.swing.JLabel();
        calendar_starDate = new com.toedter.calendar.JDateChooser();
        btn_registerLoan = new javax.swing.JButton();
        lb_messageLoan = new javax.swing.JLabel();
        lb_image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItenLibrary = new javax.swing.JMenu();
        menuItemStudent = new javax.swing.JMenuItem();
        menuItemLibrary = new javax.swing.JMenuItem();
        menuItemAudiovisual = new javax.swing.JMenuItem();
        menuLoan = new javax.swing.JMenu();
        menuItemSlect = new javax.swing.JMenuItem();
        menuItemReturn = new javax.swing.JMenuItem();
        menuItemTableStudent = new javax.swing.JMenu();
        menuItemRegisterStudent = new javax.swing.JMenuItem();
        menuItemRegisterBook = new javax.swing.JMenuItem();
        menuItemRegisterAudiovisual = new javax.swing.JMenuItem();
        MenuItem_LoanRegister = new javax.swing.JMenuItem();
        menuSystem = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_nameLoanBook.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_nameLoanBook.setForeground(new java.awt.Color(255, 255, 255));
        lb_nameLoanBook.setText("Name or code of the Book");
        getContentPane().add(lb_nameLoanBook);
        lb_nameLoanBook.setBounds(51, 93, 390, 27);

        tfx_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx_searchActionPerformed(evt);
            }
        });
        tfx_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfx_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx_searchKeyTyped(evt);
            }
        });
        getContentPane().add(tfx_search);
        tfx_search.setBounds(12, 138, 588, 30);

        txa_information.setColumns(20);
        txa_information.setRows(5);
        txa_information.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txa_informationKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txa_information);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(12, 200, 588, 229);

        tf_codeloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codeloanActionPerformed(evt);
            }
        });
        tf_codeloan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codeloanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_codeloanKeyReleased(evt);
            }
        });
        getContentPane().add(tf_codeloan);
        tf_codeloan.setBounds(880, 80, 293, 31);

        lb_codeLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_codeLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_codeLoan.setText("Code");
        getContentPane().add(lb_codeLoan);
        lb_codeLoan.setBounds(700, 80, 75, 37);

        lb_nameLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_nameLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_nameLoan.setText("Student Name");
        getContentPane().add(lb_nameLoan);
        lb_nameLoan.setBounds(690, 150, 180, 29);

        tf_nameLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameLoanActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nameLoan);
        tf_nameLoan.setBounds(880, 150, 295, 31);

        lb_idLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_idLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_idLoan.setText("Id");
        getContentPane().add(lb_idLoan);
        lb_idLoan.setBounds(710, 230, 55, 28);
        getContentPane().add(tf_idLoan);
        tf_idLoan.setBounds(880, 220, 295, 32);

        lb_dateLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_dateLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_dateLoan.setText("Date Loan");
        getContentPane().add(lb_dateLoan);
        lb_dateLoan.setBounds(700, 300, 135, 39);
        getContentPane().add(calendar_starDate);
        calendar_starDate.setBounds(880, 300, 295, 32);

        btn_registerLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        btn_registerLoan.setText("Loan");
        btn_registerLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerLoanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registerLoan);
        btn_registerLoan.setBounds(960, 450, 159, 41);

        lb_messageLoan.setFont(new java.awt.Font("Sitka Small", 1, 22)); // NOI18N
        lb_messageLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_messageLoan.setText("El prestamo se origino correctamente");
        getContentPane().add(lb_messageLoan);
        lb_messageLoan.setBounds(440, 560, 519, 34);

        lb_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo22_1.png"))); // NOI18N
        lb_image.setText("jLabel1");
        getContentPane().add(lb_image);
        lb_image.setBounds(0, -390, 2040, 1400);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuItenLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nota.png"))); // NOI18N
        menuItenLibrary.setText("Register");

        menuItemStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        menuItemStudent.setText("Students");
        menuItemStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStudentActionPerformed(evt);
            }
        });
        menuItenLibrary.add(menuItemStudent);

        menuItemLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.png"))); // NOI18N
        menuItemLibrary.setText("Books");
        menuItemLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLibraryActionPerformed(evt);
            }
        });
        menuItenLibrary.add(menuItemLibrary);

        menuItemAudiovisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/audiovisual.png"))); // NOI18N
        menuItemAudiovisual.setText("Audiovisual");
        menuItemAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAudiovisualActionPerformed(evt);
            }
        });
        menuItenLibrary.add(menuItemAudiovisual);

        jMenuBar1.add(menuItenLibrary);

        menuLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loan.png"))); // NOI18N
        menuLoan.setText("Loan");

        menuItemSlect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clave.png"))); // NOI18N
        menuItemSlect.setText("Verify");
        menuItemSlect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSlectActionPerformed(evt);
            }
        });
        menuLoan.add(menuItemSlect);

        menuItemReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espalda (1).png"))); // NOI18N
        menuItemReturn.setText("Return");
        menuItemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReturnActionPerformed(evt);
            }
        });
        menuLoan.add(menuItemReturn);

        jMenuBar1.add(menuLoan);

        menuItemTableStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nota.png"))); // NOI18N
        menuItemTableStudent.setText("Records");

        menuItemRegisterStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        menuItemRegisterStudent.setText("Students");
        menuItemRegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterStudentActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(menuItemRegisterStudent);

        menuItemRegisterBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.png"))); // NOI18N
        menuItemRegisterBook.setText("Books");
        menuItemRegisterBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterBookActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(menuItemRegisterBook);

        menuItemRegisterAudiovisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/audiovisual.png"))); // NOI18N
        menuItemRegisterAudiovisual.setText("Audiovisual");
        menuItemRegisterAudiovisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterAudiovisualActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(menuItemRegisterAudiovisual);

        MenuItem_LoanRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espalda (1).png"))); // NOI18N
        MenuItem_LoanRegister.setText("Loan");
        MenuItem_LoanRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_LoanRegisterActionPerformed(evt);
            }
        });
        menuItemTableStudent.add(MenuItem_LoanRegister);

        jMenuBar1.add(menuItemTableStudent);

        menuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro (1).png"))); // NOI18N
        menuSystem.setText("System");

        menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuSystem.add(menuItemAbout);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuSystem.add(menuItemExit);

        jMenuBar1.add(menuSystem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfx_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx_searchActionPerformed

    private void tfx_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx_searchKeyTyped


    }//GEN-LAST:event_tfx_searchKeyTyped

    private void tfx_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx_searchKeyReleased
        txa_information.setText("");

        String cadenainformativa = "";
        for (int i = 0; i < book.size(); i++) {
            if (book.get(i).search(tfx_search.getText().toUpperCase())) {
                cadenainformativa += "\n" + book.get(i).toString() + "\n";
            }
        }
        txa_information.setText(cadenainformativa);


    }//GEN-LAST:event_tfx_searchKeyReleased

    private void txa_informationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txa_informationKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txa_informationKeyReleased

    private void tf_codeloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codeloanActionPerformed

    }//GEN-LAST:event_tf_codeloanActionPerformed

    private void tf_codeloanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeloanKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_codeloanKeyReleased

    private void tf_codeloanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codeloanKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_codeloanKeyPressed

    private void tf_nameLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameLoanActionPerformed

    private void btn_registerLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerLoanActionPerformed
      archivoLoan = new File("Loan.dat");
   
        try {
            loanFile = new LoanFile(archivoLoan);
             String formato=calendar_starDate.getDateFormatString();
            Date fechainicial= calendar_starDate.getDate();
            SimpleDateFormat sdf= new SimpleDateFormat(formato);
             Loan loan=new Loan(tf_nameLoan.getText(), tf_idLoan.getText(), tf_codeloan.getText(),
             ""+ sdf.format(fechainicial));
       
        loanFile.addEndRecord(loan);
        lb_messageLoan.setVisible(true);
        lb_messageLoan.setText("El prestamo se origino correctamente");
        if(loanFile.quantityAvailable(tf_codeloan.getText())){
        }else{
            lb_messageLoan.setText("El libro no esta disponible");
        }
        tf_codeloan.setText("");
        tf_idLoan.setText("");
        tf_nameLoan.setText("");
        tf_nameLoan.setText("");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_registerLoanActionPerformed

    private void menuItemStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStudentActionPerformed
        StudentRegister sr = new StudentRegister();
        sr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemStudentActionPerformed

    private void menuItemLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLibraryActionPerformed
        BookRegister br = new BookRegister();
        br.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemLibraryActionPerformed

    private void menuItemAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAudiovisualActionPerformed
        AudiovisualRegister av = new AudiovisualRegister();
        av.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAudiovisualActionPerformed

    private void menuItemSlectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSlectActionPerformed
        LoanRegister lr = new LoanRegister();
        lr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemSlectActionPerformed

    private void menuItemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReturnActionPerformed
        ReturnBook rb;

        try {
            rb = new ReturnBook();
            rb.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuItemReturnActionPerformed

    private void menuItemRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterStudentActionPerformed
        TableStudents ts;

        try {
            ts = new TableStudents();
            ts.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_menuItemRegisterStudentActionPerformed

    private void menuItemRegisterBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterBookActionPerformed

        TableBook tb;

        try {
            tb = new TableBook();
            tb.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuItemRegisterBookActionPerformed

    private void menuItemRegisterAudiovisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterAudiovisualActionPerformed
        TableAudiovisual ta;

        try {
            ta = new TableAudiovisual();
            ta.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            System.out.println("Error");
        } catch (ClassNotFoundException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_menuItemRegisterAudiovisualActionPerformed

    private void MenuItem_LoanRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_LoanRegisterActionPerformed
        TableLoan tl;

        try {
            tl = new TableLoan();
            tl.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            System.out.println("Error");
        } catch (ClassNotFoundException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_MenuItem_LoanRegisterActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        About ab = new About();
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoanBook().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoanBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_LoanRegister;
    private javax.swing.JButton btn_registerLoan;
    public static com.toedter.calendar.JDateChooser calendar_starDate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_codeLoan;
    private javax.swing.JLabel lb_dateLoan;
    private javax.swing.JLabel lb_idLoan;
    private javax.swing.JLabel lb_image;
    private javax.swing.JLabel lb_messageLoan;
    private javax.swing.JLabel lb_nameLoan;
    private javax.swing.JLabel lb_nameLoanBook;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemAudiovisual;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLibrary;
    private javax.swing.JMenuItem menuItemRegisterAudiovisual;
    private javax.swing.JMenuItem menuItemRegisterBook;
    private javax.swing.JMenuItem menuItemRegisterStudent;
    private javax.swing.JMenuItem menuItemReturn;
    private javax.swing.JMenuItem menuItemSlect;
    private javax.swing.JMenuItem menuItemStudent;
    private javax.swing.JMenu menuItemTableStudent;
    private javax.swing.JMenu menuItenLibrary;
    private javax.swing.JMenu menuLoan;
    private javax.swing.JMenu menuSystem;
    private javax.swing.JTextField tf_codeloan;
    private javax.swing.JTextField tf_idLoan;
    private javax.swing.JTextField tf_nameLoan;
    private javax.swing.JTextField tfx_search;
    private javax.swing.JTextArea txa_information;
    // End of variables declaration//GEN-END:variables
}
